config/routes.rb
Rails.application.routes.draw do

  get '/pricing', to: 'home#pricing'
  post '/subscribe', to: 'payment#subscribe'

  resource :sessions, only: [:new, :create] do
    member do
      get :destroy, as: 'destroy'
    end
  end
  root :to => 'home#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :password, length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @user ||= User.find(session[:user_id])
  end

  protected

  def require_user
    if session[:user_id].blank?
      redirect_to new_sessions_path
      return
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

end

app/controllers/payment_controller.rb
class PaymentController < ApplicationController
  before_action :require_user

  def subscribe
    begin
    if current_user.stripe_customer_id.present?
      customer = Stripe::Customer.retrieve(current_user.stripe_customer_id)
    else
      customer = Stripe::Customer.create(email: current_user.username, card: params[:stripe_card_token])
      current_user.update_attribute(:stripe_customer_id, customer.id)
    end

    plan_id = Rails.configuration.stripe[params['plan'].to_sym]
    customer.subscriptions.create({:plan => plan_id})

    redirect_to root_path
    rescue Stripe::CardError
      render 'home/pricing'
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(username: params[:username].downcase)
    if user && user.authenticate( params[:password] )
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash[:error] = "Invalid email or password :("
      render action: 'new'
    end
  end

  def destroy
    session.delete :user_id
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.haml
%h1 Songs List
%ul
  %li Abcdf
  %li Abcdf
  %li Abcdf
  %li Abcdf
  %li Abcdf

app/views/home/pricing.html.haml
%h1 Pricing
= form_tag subscribe_path, method: 'POST', id: 'new_subscription' do |f|
  %label Basic Plan
  = radio_button_tag 'plan', 'basic_plan_id'
  %label Premium Plan
  = radio_button_tag 'plan', 'premium_plan_id'
  = hidden_field_tag 'stripe_card_token'
  %h3#stripe_error
  %label Credit Card
  %input{:type => "text", id: 'credit_card_number'}
  %br
  = label_tag :card_month, "Card Expiration"
  = select_month nil, {add_month_numbers: true}, {name: nil, id: "card_month"}
  = select_year nil, {start_year: Date.today.year, end_year: Date.today.year+15}, {name: nil, id: "card_year"}
  %br
  %label Security Code
  %input{:type => "text", id: 'security_code'}/
  %br
  %button{:type => "submit"} Register
%script{:src => "https://js.stripe.com/v2/", :type => "text/javascript"}
%script Stripe.setPublishableKey("#{Rails.configuration.stripe[:publishable_key]}");

app/views/layouts/application.html.haml
%html{:lang => "en"}
  %head
    %title StripeTutorial
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
  %body
    .container
      .navbar
        = link_to 'Songs', '#', class: 'btn btn-default'
        .pull_right
          - if session[:user_id]
            = link_to 'Subscribe', pricing_path, class: 'btn btn-default'
            = link_to 'Log Out', destroy_sessions_path, class: 'btn btn-default'
          - else
            = link_to 'Sign In', new_sessions_path, class: 'btn btn-default'
      .box.well
        = yield